# Autogenerated wrapper script for OSQP_jll for x86_64-apple-darwin
export osqp

JLLWrappers.@generate_wrapper_header("OSQP")
JLLWrappers.@declare_library_product(osqp, "@rpath/libosqp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        osqp,
        "lib/libosqp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
