# Autogenerated wrapper script for OSQP_jll for x86_64-linux-gnu
export codegen_files_dir, osqp_builtin

JLLWrappers.@generate_wrapper_header("OSQP")
JLLWrappers.@declare_file_product(codegen_files_dir)
JLLWrappers.@declare_library_product(osqp_builtin, "libosqp_builtin.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        codegen_files_dir,
        "share/osqp/codegen_files",
    )

    JLLWrappers.@init_library_product(
        osqp_builtin,
        "lib/libosqp_builtin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
